import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export async function formatCode(code: string, language: string = 'typescript'): Promise<string> {
  if (!code) return '';
  
  try {
    // Map languages to prettier parsers
    let parser = 'typescript';
    const lang = language.toLowerCase();
    if (lang === 'javascript' || lang === 'jsx' || lang === 'js') parser = 'babel';
    if (lang === 'typescript' || lang === 'tsx' || lang === 'ts') parser = 'typescript';
    if (lang === 'json') parser = 'json';
    if (lang === 'markdown' || lang === 'md') parser = 'markdown';
    if (lang === 'html') parser = 'html';
    if (lang === 'css' || lang === 'scss' || lang === 'less') parser = 'postcss';

    // Lazy load Prettier and plugins
    const [prettier, babelParser, estreeParser, tsParser, markdownParser, htmlParser] = await Promise.all([
      import("prettier/standalone"),
      import("prettier/plugins/babel"),
      import("prettier/plugins/estree"),
      import("prettier/plugins/typescript"),
      import("prettier/plugins/markdown"),
      import("prettier/plugins/html")
    ]);

    return await (prettier.default || prettier).format(code, {
      parser,
      plugins: [
        babelParser.default || babelParser,
        estreeParser.default || estreeParser,
        tsParser.default || tsParser,
        markdownParser.default || markdownParser,
        htmlParser.default || htmlParser
      ],
      semi: true,
      singleQuote: true,
      trailingComma: 'es5',
      printWidth: 80,
      tabWidth: 2,
    });
  } catch (error) {
    console.warn('Prettier formatting failed:', error);
    return code; // Return original code if formatting fails
  }
}

export async function warmupPrettier() {
  try {
    // Just trigger the dynamic imports to prime the cache
    await Promise.all([
      import("prettier/standalone"),
      import("prettier/plugins/babel"),
      import("prettier/plugins/estree"),
      import("prettier/plugins/typescript"),
      import("prettier/plugins/markdown"),
      import("prettier/plugins/html")
    ]);
  } catch (e) {
    // Silent fail for warmup
  }
}

export function generateMarkdown(review: any): string {
  const date = new Date().toLocaleDateString();
  const md = [
    `# Nexis: Engineering Review Report`,
    `> Generated on ${date} | Confidence Index: ${review.confidenceLevel.toUpperCase()}`,
    ``,
    `## 📊 Executive Audit Scores`,
    `| Metric | Status |`,
    `| :--- | :--- |`,
    `| **Performance** | ${review.scores.performance} / 10 |`,
    `| **Readability** | ${review.scores.readability} / 10 |`,
    `| **Maintainability** | ${review.scores.maintainability} / 10 |`,
    ``,
    `### Summary`,
    `${review.summary}`,
    ``,
    `## 🔴 Critical Vulnerabilities`,
    review.criticalIssues.length === 0 ? "_No critical vulnerabilities detected._" : 
    review.criticalIssues.map((issue: any) => (
      `### [${issue.severity.toUpperCase()}] ${issue.title}\n` +
      `**Impact:** ${issue.impact}\n\n` +
      `${issue.description}\n`
    )).join('\n'),
    ``,
    `## ⚡ Execution Profiling`,
    `- **Peak Time Complexity:** \`${review.performanceAnalysis.timeComplexity}\``,
    `- **Memory Footprint:** ${review.performanceAnalysis.memoryEfficiency}`,
    `- **Active Bottlenecks:**`,
    review.performanceAnalysis.bottlenecks.map((b: string) => `  - ${b}`).join('\n'),
    ``,
    `## 🔧 Refactoring Directives`,
    review.refactoringSuggestions.map((ref: any) => (
      `### Optimization: ${ref.explanation}\n` +
      `#### Existing Pattern\n` +
      `\`\`\`typescript\n${ref.before}\n\`\`\`\n` +
      `#### Optimized Pattern\n` +
      `\`\`\`typescript\n${ref.after}\n\`\`\`\n`
    )).join('\n'),
    ``,
    `## 🗺️ Process Flow (Mermaid)`,
    `\`\`\`mermaid\n${review.logicalFlow}\n\`\`\``,
    ``,
    `## 📖 Plain English Logic`,
    `${review.simplifiedExplanation}`,
    ``,
    `## 📚 JSDoc Technical Reference`,
    review.documentation.map((doc: any) => (
      `### \`${doc.functionName}()\`\n` +
      `**Description:** ${doc.description}\n` +
      `**Returns:** \`${doc.returns}\`\n` +
      `\`\`\`javascript\n/**\n * ${doc.description}\n${doc.parameters.map((p: string) => ` * @param ${p}`).join('\n')}\n * @returns ${doc.returns}\n */\n\`\`\`\n`
    )).join('\n'),
    ``,
    `---`,
    `_Generated by Nexis - Principal Analysis Engine_`
  ].join('\n');

  return md;
}

export function downloadFile(content: string, fileName: string, contentType: string) {
  const a = document.createElement("a");
  const file = new Blob([content], { type: contentType });
  a.href = URL.createObjectURL(file);
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(a.href);
}

export function replaceOklch(cssText: string | null): string {
  if (!cssText) return '';
  
  // 1. Convert oklch to hsl/hsla
  let output = cssText.replace(/oklch\(\s*([0-9.]+%?)\s*[\s,]\s*([0-9.]+%?)\s*[\s,]\s*([-+0-9.]+%?)(?:\s*[\/,\s]\s*([0-9.]+%?))?\s*\)/g, (match, lStr, cStr, hStr, aStr) => {
    try {
      // Parse L
      let l = parseFloat(lStr);
      if (lStr.includes('%')) {
        // already percentage
      } else {
        l = l * 100; // e.g. 0.79 -> 79
      }
      
      // Parse C (0 to 0.4 usually)
      const c = parseFloat(cStr);
      const s = Math.min(100, Math.max(0, c * 250)); // chroma to saturation percentage approximation
      
      // Parse H (0 to 360)
      const h = parseFloat(hStr);
      
      // Parse Alpha
      if (aStr) {
        let a = parseFloat(aStr);
        if (aStr.includes('%')) {
          a = a / 100;
        }
        return `hsla(${h}, ${Math.round(s)}%, ${Math.round(l)}%, ${a})`;
      } else {
        return `hsl(${h}, ${Math.round(s)}%, ${Math.round(l)}%)`;
      }
    } catch {
      return 'rgb(16, 185, 129)'; // safe fallback emerald-500
    }
  });

  // 2. Convert oklab to hsl/hsla
  output = output.replace(/oklab\(\s*([0-9.]+%?)\s*[\s,]\s*([-+0-9.]+%?)\s*[\s,]\s*([-+0-9.]+%?)(?:\s*[\/,\s]\s*([0-9.]+%?))?\s*\)/g, (match, lStr, aValStr, bValStr, aStr) => {
    try {
      let l = parseFloat(lStr);
      if (lStr.includes('%')) {
        // already percentage
      } else {
        l = l * 100;
      }
      
      const aVal = parseFloat(aValStr);
      const bVal = parseFloat(bValStr);
      
      // Convert Cartesian (a, b) to Cylindrical (chroma C, hue H)
      const c = Math.sqrt(aVal * aVal + bVal * bVal);
      let h = (Math.atan2(bVal, aVal) * 180) / Math.PI;
      h = (h + 360) % 360;
      
      const s = Math.min(100, Math.max(0, c * 250)); // chroma to saturation approximation

      if (aStr) {
        let a = parseFloat(aStr);
        if (aStr.includes('%')) {
          a = a / 100;
        }
        return `hsla(${h}, ${Math.round(s)}%, ${Math.round(l)}%, ${a})`;
      } else {
        return `hsl(${h}, ${Math.round(s)}%, ${Math.round(l)}%)`;
      }
    } catch {
      return 'rgb(16, 185, 129)';
    }
  });

  return output;
}

export function cleanGlobalStyles() {
  // Process all <style> elements
  const styles = document.querySelectorAll('style');
  styles.forEach((style) => {
    if (style.textContent && (style.textContent.includes('oklch') || style.textContent.includes('oklab')) && !style.classList.contains('nexis-inlined')) {
      style.textContent = replaceOklch(style.textContent);
    }
  });

  // Process all same-origin <link> elements to inline safe versions
  const links = document.querySelectorAll('link[rel="stylesheet"]');
  links.forEach(async (linkNode) => {
    const link = linkNode as HTMLLinkElement;
    if (link.href && (link.href.startsWith(window.location.origin) || link.href.startsWith('/')) && !link.classList.contains('nexis-processed')) {
      try {
        link.classList.add('nexis-processed');
        const res = await fetch(link.href);
        if (res.ok) {
          const rawText = await res.text();
          const cleanText = replaceOklch(rawText);
          const styleEl = document.createElement('style');
          styleEl.classList.add('nexis-inlined');
          styleEl.textContent = cleanText;
          document.head.appendChild(styleEl);
          
          // disable/remove link
          link.disabled = true;
          if (link.parentNode) {
            link.parentNode.removeChild(link);
          }
        }
      } catch (err) {
        console.warn("Clean style inlining failed:", link.href, err);
      }
    }
  });
}

export function observeAndCleanStyles() {
  if (typeof window === 'undefined') return;
  
  // Initial run
  cleanGlobalStyles();
  
  const observer = new MutationObserver((mutations) => {
    let shouldScan = false;
    for (const m of mutations) {
      if (m.type === 'childList') {
        m.addedNodes.forEach(node => {
          if (node.nodeName === 'STYLE' || node.nodeName === 'LINK') {
            shouldScan = true;
          }
        });
      } else if (m.type === 'attributes' && m.attributeName === 'style') {
        const elem = m.target as HTMLElement;
        if (elem && typeof elem.getAttribute === 'function') {
          const styleAttr = elem.getAttribute('style');
          if (styleAttr && (styleAttr.includes('oklch') || styleAttr.includes('oklab'))) {
            observer.disconnect();
            elem.setAttribute('style', replaceOklch(styleAttr));
            observer.observe(document.documentElement, {
              childList: true,
              subtree: true,
              attributes: true,
              attributeFilter: ['style']
            });
          }
        }
      }
    }
    if (shouldScan) {
      cleanGlobalStyles();
    }
  });

  observer.observe(document.documentElement, {
    childList: true,
    subtree: true,
    attributes: true,
    attributeFilter: ['style']
  });
}

