import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export async function formatCode(code: string, language: string = 'typescript'): Promise<string> {
  if (!code) return '';
  
  try {
    // Map languages to prettier parsers
    let parser = 'typescript';
    const lang = language.toLowerCase();
    if (lang === 'javascript' || lang === 'jsx' || lang === 'js') parser = 'babel';
    if (lang === 'typescript' || lang === 'tsx' || lang === 'ts') parser = 'typescript';
    if (lang === 'json') parser = 'json';
    if (lang === 'markdown' || lang === 'md') parser = 'markdown';
    if (lang === 'html') parser = 'html';
    if (lang === 'css' || lang === 'scss' || lang === 'less') parser = 'postcss';

    // Lazy load Prettier and plugins
    const [prettier, babelParser, estreeParser, tsParser, markdownParser, htmlParser] = await Promise.all([
      import("prettier/standalone"),
      import("prettier/plugins/babel"),
      import("prettier/plugins/estree"),
      import("prettier/plugins/typescript"),
      import("prettier/plugins/markdown"),
      import("prettier/plugins/html")
    ]);

    return await (prettier.default || prettier).format(code, {
      parser,
      plugins: [
        babelParser.default || babelParser,
        estreeParser.default || estreeParser,
        tsParser.default || tsParser,
        markdownParser.default || markdownParser,
        htmlParser.default || htmlParser
      ],
      semi: true,
      singleQuote: true,
      trailingComma: 'es5',
      printWidth: 80,
      tabWidth: 2,
    });
  } catch (error) {
    console.warn('Prettier formatting failed:', error);
    return code; // Return original code if formatting fails
  }
}

export async function warmupPrettier() {
  try {
    // Just trigger the dynamic imports to prime the cache
    await Promise.all([
      import("prettier/standalone"),
      import("prettier/plugins/babel"),
      import("prettier/plugins/estree"),
      import("prettier/plugins/typescript"),
      import("prettier/plugins/markdown"),
      import("prettier/plugins/html")
    ]);
  } catch (e) {
    // Silent fail for warmup
  }
}

export function generateMarkdown(review: any): string {
  const date = new Date().toLocaleDateString();
  const md = [
    `# CodeSentinel: Engineering Review Report`,
    `> Generated on ${date} | Confidence Index: ${review.confidenceLevel.toUpperCase()}`,
    ``,
    `## 📊 Executive Audit Scores`,
    `| Metric | Status |`,
    `| :--- | :--- |`,
    `| **Performance** | ${review.scores.performance} / 10 |`,
    `| **Readability** | ${review.scores.readability} / 10 |`,
    `| **Maintainability** | ${review.scores.maintainability} / 10 |`,
    ``,
    `### Summary`,
    `${review.summary}`,
    ``,
    `## 🔴 Critical Vulnerabilities`,
    review.criticalIssues.length === 0 ? "_No critical vulnerabilities detected._" : 
    review.criticalIssues.map((issue: any) => (
      `### [${issue.severity.toUpperCase()}] ${issue.title}\n` +
      `**Impact:** ${issue.impact}\n\n` +
      `${issue.description}\n`
    )).join('\n'),
    ``,
    `## ⚡ Execution Profiling`,
    `- **Peak Time Complexity:** \`${review.performanceAnalysis.timeComplexity}\``,
    `- **Memory Footprint:** ${review.performanceAnalysis.memoryEfficiency}`,
    `- **Active Bottlenecks:**`,
    review.performanceAnalysis.bottlenecks.map((b: string) => `  - ${b}`).join('\n'),
    ``,
    `## 🔧 Refactoring Directives`,
    review.refactoringSuggestions.map((ref: any) => (
      `### Optimization: ${ref.explanation}\n` +
      `#### Existing Pattern\n` +
      `\`\`\`typescript\n${ref.before}\n\`\`\`\n` +
      `#### Optimized Pattern\n` +
      `\`\`\`typescript\n${ref.after}\n\`\`\`\n`
    )).join('\n'),
    ``,
    `## 🗺️ Process Flow (Mermaid)`,
    `\`\`\`mermaid\n${review.logicalFlow}\n\`\`\``,
    ``,
    `## 📖 Plain English Logic`,
    `${review.simplifiedExplanation}`,
    ``,
    `## 📚 JSDoc Technical Reference`,
    review.documentation.map((doc: any) => (
      `### \`${doc.functionName}()\`\n` +
      `**Description:** ${doc.description}\n` +
      `**Returns:** \`${doc.returns}\`\n` +
      `\`\`\`javascript\n/**\n * ${doc.description}\n${doc.parameters.map((p: string) => ` * @param ${p}`).join('\n')}\n * @returns ${doc.returns}\n */\n\`\`\`\n`
    )).join('\n'),
    ``,
    `---`,
    `_Generated by CodeSentinel - Principal Analysis Engine_`
  ].join('\n');

  return md;
}

export function downloadFile(content: string, fileName: string, contentType: string) {
  const a = document.createElement("a");
  const file = new Blob([content], { type: contentType });
  a.href = URL.createObjectURL(file);
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(a.href);
}
